name=LTC1594
version=1.0.1
author=Souvik Saha <souvikssaha@gmail.com>, Ludo Nulens
maintainer=Ludo Nulens
sentence=Arduino library for the 12-bit LTC1594 ADC by Linear Technology.
paragraph=The LTC1594 is a 4-channel 12-bit ADC that operates from a 5 V supply and communicates over SPI.
category=Signal Input/Output
url=https://github.com/Nulista/LTC1594
architectures=avr,megaavr,esp8266
includes=LTC1594.h
